[package]
name = "nw-network-types"
version = "0.1.0"
edition = "2024"
description = "Generated data types used by nw-network."
license = "MIT OR Apache-2.0"
repository = "https://github.com/themixednuts/nw-network"

[dependencies]
arrayvec = { version = "0.7.7", features = ["serde"] }
bevy_app = "0.19"
bevy_ecs = { version = "0.19", features = ["serialize"] }
bevy_color = { version = "0.19", features = ["serialize"] }
bevy_math = { version = "0.19", features = ["serialize"] }
bevy_reflect = { version = "0.19", features = ["smallvec", "uuid"] }
bevy_transform = { version = "0.19", features = ["serialize"] }
sha1 = "0.11"
serde = { version = "1", features = ["derive"] }
smallvec = { version = "1", features = ["serde"] }
uuid = { version = "1.23", features = ["serde", "v4", "v7"] }

[build-dependencies]
anyhow = "1"
blake3 = "1"
nw-resources = { git = "https://github.com/themixednuts/nw-tools.git", rev = "d1714993a0921f556dd98dbc737b1f9cb7decaab" }
nw-serialize-codegen = { git = "https://github.com/themixednuts/nw-tools.git", rev = "d1714993a0921f556dd98dbc737b1f9cb7decaab" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
